version: '3'
services:
  dynamo:
    container_name: dynamodb
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    # TODO: Get a host OS local not-in-git directory in project to save
    # data to.
    # volumes:
    #  - <directory>:/home/dynamodblocal/data
    # working_dir: /home/dynamodblocal
    # command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "./data"]
